### ISSUE TITLE
search_scopus issues

### ISSUE THREAD

**Issue by judiths1618** [NLeSC/automated-literature-analysis#4]
Hi, there're some problems with me when i run the code cell with 
```
scopus_query = 'title-abs-key(medical data sharing)'
docset = litstudy.search_scopus(scopus_query, docset)
```
In detail, it gave me the tips with 

>  ---------------------------------------------------------------------------
> Scopus401Error                            Traceback (most recent call last)
>  in 
>       4 
>       5 scopus_query = 'title-abs-key(medical data sharing)'
> ----> 6 docset = litstudy.search_scopus(scopus_query, docset)
> 
> c:\Users\Judiths\Desktop\CLARIFY survey\automated-literature-analysis\litstudy\search.py in search_scopus(query, docs, retrieve_orcid)
>      78     affiliations_cache = {}
>      79     try:
> ---> 80         retrieved_paper_ids = ScopusSearch(query, view="STANDARD").get_eids()
>      81     except ScopusQueryError:
>      82         print("Impossible to process query \"{}\".".format(query))
> 
> c:\users\judiths\anaconda3\envs\mysurvey\lib\site-packages\pybliometrics\scopus\scopus_search.py in __init__(self, query, refresh, subscriber, view, download, integrity_fields, integrity_action, verbose, **kwds)
>     195         Search.__init__(self, query=query, api='ScopusSearch', refresh=refresh,
>     196                         count=count, cursor=subscriber, view=view,
> --> 197                         download=download, verbose=verbose, **kwds)
>     198         self.integrity = integrity_fields or []
>     199         self.action = integrity_action
> 
> c:\users\judiths\anaconda3\envs\mysurvey\lib\site-packages\pybliometrics\scopus\classes\search.py in __init__(self, query, api, refresh, view, count, max_entries, cursor, download, verbose, **kwds)
>      77                 params.update({'start': 0})
>      78             # Download results
> ---> 79             res = cache_file(url=SEARCH_URL[api], params=params, **kwds).json()
>      80             n = int(res['search-results'].get('opensearch:totalResults', 0))
>      81             self._n = n
> 
> c:\users\judiths\anaconda3\envs\mysurvey\lib\site-packages\pybliometrics\scopus\utils\get_content.py in cache_file(url, params, **kwds)
>      74             except:
>      75                 reason = ""
> ---> 76             raise errors[resp.status_code](reason)
>      77         else:
>      78             resp.raise_for_status()
> 
> Scopus401Error: Invalid API Key

i have successfully installed the python virtual environment, but it's wrong when i run the code. i don't know if it's the code bugs or not. if you know the reasons why it happened, could you please answer me?

**Comment by isazi** [comment]
Hi, does the error occur only with this query or with any query?

**Comment by judiths1618** [comment]
Hi, I tried other query (key words)
scopus_query = 'title-abs-key(cloud computing)'
scopus_query = 'title-abs-key(workflow scheduling)'

The error still occur.

Sincerely,
Yuandou Wang

发件人: Alessio Sclocco<mailto:notifications@github.com>
发送时间: 2020年4月30日 16:14
收件人: NLeSC/automated-literature-analysis<mailto:automated-literature-analysis@noreply.github.com>
抄送: judiths1618<mailto:judiths11@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [NLeSC/automated-literature-analysis] search_scopus issues (#4)


Hi, does the error occur only with this query or with any query?

―

**Comment by isazi** [comment]
Another question, can you try to execute the included python notebook? The file is  literature_analysis.ipynb

**Comment by isazi** [comment]
I'll close this one for one, feel free to reopen it if you have again problems.

**Comment by judiths1618** [comment]
Hi, do you know the “Scopus400Error” ?
Recently, I git clone your project on the centos and executed the jupyter notebook on the server with configuration of  the .scopus APIkey, the before problem seems to be solved. However, another issue happened, in detail, the results are like this:
[cid:image002.png@01D6250F.BB5D4F40]
I checked the search API  of the scopus and the query, neither of them are wrong. Can you help me with the problem?

Sincerely,
Yuandou Wang

发件人: Alessio Sclocco<mailto:notifications@github.com>
发送时间: 2020年5月7日 20:55
收件人: NLeSC/automated-literature-analysis<mailto:automated-literature-analysis@noreply.github.com>
抄送: judiths1618<mailto:judiths11@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [NLeSC/automated-literature-analysis] search_scopus issues (#4)


Closed #4<https://github.com/NLeSC/automated-literature-analysis/issues/4>.

―

**Comment by judiths1618** [comment]
Hi, I have known the reasons why I got such problems:


1)     Didn’t correctly configure the .scopus/config.ini with the APIKey;

2)     Didn’t access to “ScopusSearch” with an accessible network of the University (institution).

Well, after I solved the above problems, it seems to me that everything works well.

Sincerely,
Yuandou Wang

发件人: Alessio Sclocco<mailto:notifications@github.com>
发送时间: 2020年5月7日 20:55
收件人: NLeSC/automated-literature-analysis<mailto:automated-literature-analysis@noreply.github.com>
抄送: judiths1618<mailto:judiths11@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [NLeSC/automated-literature-analysis] search_scopus issues (#4)


I'll close this one for one, feel free to reopen it if you have again problems.

―

**Comment by isazi** [comment]
Thank for letting us know. Bye!

**Comment by judiths1618** [comment]
you are welcome. bye bye~
--
从Outlook Email App的Android专用app所发送 星期五, 08 五月 2020, 04:47下午 +08:00 发件人 Alessio Sclocco  notifications@github.com :
